// Content for the Fotografía page, kept separate from the UI like business.ts.
//
// HOW TO ADD PHOTOS TO THE GALLERY:
// 1. Place the original files in the source folder (one subfolder per
//    collection; loose ones at the root) — see PHOTOS_SRC_DIR in scripts/photos-sync.mjs.
// 2. Run `npm run photos:sync` (requires a local .env with Supabase
//    credentials, see .env.example). It optimizes, uploads to Supabase
//    Storage, and regenerates src/data/gallery.generated.ts automatically.
// 3. Commit the regenerated manifest.

import { galleryManifest } from './gallery.generated';

export type PhotoCategory = 'eventos' | 'retratos' | 'producto' | 'paisaje';

export interface GalleryPhoto {
  thumbSrc: string;
  fullSrc: string;
  alt: string;
  width: number; // intrinsic width of the full variant → aspect-ratio, no layout shift
  height: number; // intrinsic height of the full variant
  collection: string | null; // display credit; null = loose photos with no collection
  lqip?: string; // base64 blur placeholder (data URI)
}

export interface PhotoPackage {
  name: string;
  target: string;
  price: string;
  includes: string[];
  isFeatured?: boolean;
}

export const photoCategories: { key: PhotoCategory; label: string; desc: string }[] = [
  {
    key: 'eventos',
    label: 'Eventos',
    desc: 'Cobertura de eventos culturales y sociales: el registro fiel de lo que pasó.',
  },
  {
    key: 'retratos',
    label: 'Retratos & Books',
    desc: 'Sesiones personales y books profesionales, en estudio o locación.',
  },
  {
    key: 'producto',
    label: 'Producto',
    desc: 'Fotografía de producto para e-commerce y redes: tu catálogo listo para vender.',
  },
  {
    key: 'paisaje',
    label: 'Paisaje & Arte',
    desc: 'Obra personal de paisaje, disponible como impresión.',
  },
];

// Real photos are added following the instructions above: this array is not
// edited by hand, it's generated by `npm run photos:sync` in gallery.generated.ts.
export const galleryPhotos: GalleryPhoto[] = galleryManifest;

// EDITAR: precios y alcances de referencia; ajustar antes de publicar.
export const photoPackages: PhotoPackage[] = [
  {
    name: 'Evento',
    target: 'Eventos culturales, sociales y corporativos.',
    price: 'A convenir',
    includes: [
      'Cobertura por hora o jornada completa',
      'Selección y edición profesional',
      'Galería digital privada para descargar',
      'Entrega express de destacadas (24 hs)',
    ],
  },
  {
    name: 'Retrato / Book',
    target: 'Books profesionales, perfiles y sesiones personales.',
    price: 'A convenir',
    includes: [
      'Sesión en estudio o locación',
      'Asesoramiento de vestuario y poses',
      'Fotos editadas en alta resolución',
      'Versiones optimizadas para redes',
    ],
    isFeatured: true,
  },
  {
    name: 'Producto para marcas',
    target: 'Catálogos e-commerce, gastronomía y redes sociales.',
    price: 'A convenir',
    includes: [
      'Fotografía de producto con fondo neutro o ambientada',
      'Optimización para tienda online (peso y formato)',
      'Pack de imágenes para redes',
      'Descuento combinado con el servicio de desarrollo web',
    ],
  },
];
